In [1]:
print("hello")

hello


In [3]:
print('hello')

hello


In [6]:
a=[1,2,3]
print(a)
print(type(a))

[1, 2, 3]
<class 'list'>


[[1, 2, 3], [4, 5]]
<class 'list'>


In [10]:
import numpy as np
c=np.array(a)
type(c)



NameError: name 'a' is not defined

In [32]:
b=[[9,8],[9,0]]
print(b)
print(type(b))

d=np.array(b)
print(d)

[[9, 8], [9, 0]]
<class 'list'>
[[9 8]
 [9 0]]


In [33]:
d.ndim

2

<class 'numpy.ndarray'>


In [27]:
d.ndim

1

In [28]:
g=[[[0,2],[2,3]],[[1,2],[2,3]]]
f=np.array(g)
f.ndim

3

In [35]:
f.shape

(2, 2, 2)

In [36]:
f.size

8

In [39]:
f.dtype

dtype('int32')

In [40]:
f.itemsize

4

In [41]:
f.data

In [11]:
import numpy as np
np.zeros((5,5))


array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [3]:
import numpy as np
np.ones((2,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])