In [5]:
#range
import numpy as np



f=np.arange(2,21,2)
print(f)

[ 2  4  6  8 10 12 14 16 18 20]


In [7]:
#hstack
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[0,2,4],[6,8,9]])
arr1


array([[0, 2, 4],
       [6, 8, 9]])

In [8]:
arr2

array([[0, 2, 4],
       [6, 8, 9]])

In [9]:
c=np.hstack([arr1,arr2])
c

array([[1, 2, 3, 0, 2, 4],
       [4, 5, 6, 6, 8, 9]])

In [10]:
#vstack
d=np.vstack([arr1,arr2])
d

array([[1, 2, 3],
       [4, 5, 6],
       [0, 2, 4],
       [6, 8, 9]])

In [13]:
h=np.arange(13,132,13)
h

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [15]:
#linear space
ab=np.linspace(1.0,5.0,num=10)
ab

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [16]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr1.shape

(2, 3)

In [20]:
arr1.size

6

In [22]:
arr1[0:1]

array([[1, 2, 3]])

In [23]:
arr1[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
arr1[1:2]

array([[4, 5, 6]])

In [28]:
arr1[:,2]

array([3, 6])

In [29]:
arr1[:,1]

array([2, 5])

In [30]:
arr1[:,0]

array([1, 4])

In [31]:
#1st row second column
arr1[1:,2]

array([6])

In [33]:
arr1[0:1,2]

array([3])

In [58]:
one=np.ones((4,4))
one

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [44]:
import numpy as np
arr=np.random.randint(0,20,size=(3,2))
print(arr.shape)
arr

(3, 2)


array([[10, 18],
       [14, 17],
       [17,  3]])

In [41]:
arr=np.array([1,2,3,4,5])
arr += -5
arr

array([-4, -3, -2, -1,  0])

In [42]:
arr=np.array([1,2,3,4,5])
arr += 5
arr

array([ 6,  7,  8,  9, 10])

In [50]:
arr=np.random.randint(0,15,size=(3,2))
print(arr)
print(arr.min())
print(arr.max())


[[2 4]
 [6 6]
 [0 9]]
0
9


In [53]:
arr=np.random.randint(0,15,size=(3,2))
print(arr)
print(arr.shape)
print("After reshape")
arr=arr.reshape(2,3)
print(arr)

[[ 9 13]
 [13  1]
 [11  4]]
(3, 2)
After reshape
[[ 9 13 13]
 [ 1 11  4]]


In [56]:
arr=np.random.randint(0,10,size=(3,3))
print(arr)
print(arr.shape)
print("After reshape")
arr=arr.reshape(9,1)
print(arr)

[[3 3 1]
 [8 6 1]
 [8 1 0]]
(3, 3)
After reshape
[[3]
 [3]
 [1]
 [8]
 [6]
 [1]
 [8]
 [1]
 [0]]


In [59]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.add(a,b)
c

array([5, 7, 9])

In [62]:
zero=np.zeros((5,2))
zero

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [63]:
one=np.ones((3,3))
one

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [66]:
#Transform
a=np.array([[1,2],[3,4]])
a
a=a.T
print(a)

[[1 3]
 [2 4]]
