In [1]:
print("HELLO")

HELLO


In [2]:
a=[1,2,3]
print(a)

[1, 2, 3]


In [3]:
type(a)

list

In [14]:
b=[[[1,2,3],[4,5],[6]]]
print(b)
type(b)
c=np.array(b)
c.ndim


[[[1, 2, 3], [4, 5], [6]]]


2

In [24]:
x=[[[1,2],[2,3],[3,4],[4,5]]]
y=np.array(x)
y.ndim

3

In [18]:
y.shape

(1, 4, 2)

In [19]:
y.size

8

In [25]:
y.dtype

dtype('int32')

In [26]:
import numpy as np
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
np.ones((1,3))

array([[ 1.,  1.,  1.]])

In [27]:
y.itemsize

4

In [1]:
import numpy as np
arr=np.array([1,2,3])
print(arr)


[1 2 3]


In [2]:
#copy
abc=np.copy(arr)
print(abc)

[1 2 3]


In [6]:
#view datatype
arr.view(dtype='float32')


array([  1.40129846e-45,   2.80259693e-45,   4.20389539e-45], dtype=float32)

In [7]:
arr.sort()
print(arr)

[1 2 3]


In [8]:
#sort
xyz=np.array([7,2,9,1,4])
print(xyz)
xyz.sort()
print(xyz)

[7 2 9 1 4]
[1 2 4 7 9]


In [9]:
#reshape
mn=np.array([[3,4,5],[9,4,6]])
p=mn.reshape(1,6)
print(p)

[[3 4 5 9 4 6]]


In [11]:
#reshape
p=mn.reshape(6,1)
print(p)

[[3]
 [4]
 [5]
 [9]
 [4]
 [6]]


In [12]:
#append
xy=np.append(mn,[3,4,5])
print(xy)

[3 4 5 9 4 6 3 4 5]


In [13]:
print(mn)

[[3 4 5]
 [9 4 6]]


In [14]:
#insert
h=np.array([3,4,5,6])
i=np.insert(h,3,70)
print(i)


[ 3  4  5 70  6]


In [15]:
#delete
w=np.delete(h,2)
print(w)

[3 4 6]


In [19]:
#Combining
array1=np.array([9,4,1,7,0])
array2=np.array([4,2,7,1,0])
v=np.concatenate((array1,array2),axis=0)
print(v)

[9 4 1 7 0 4 2 7 1 0]


In [21]:
#concatenate
array3=np.array([[9,4,1,7,0],[8,4,5,1,9]])
array4=np.array([[4,2,7,1,0],[6,7,8,9,4]])
s=np.concatenate((array3,array4),axis=1)
print(s)

[[9 4 1 7 0 4 2 7 1 0]
 [8 4 5 1 9 6 7 8 9 4]]


In [29]:
#split
array5=np.array([8,0,5,4,1,2,9,0,0,4])
s=np.split(array5,2)
print(s)

[array([8, 0, 5, 4, 1]), array([2, 9, 0, 0, 4])]


In [27]:
#index
s=array5[9]
print(s)

4


In [33]:
#assign value to index
s=array5[9]=8
print(s)
print(array5)

8
[8 0 5 4 1 2 9 0 0 8]


In [26]:
#indexing
array5=np.array([8,0,5,4,1,2,9,0,0,4])
s=array5[1:3]=8
print(s)
print(array5)

8
[8 8 8 4 1 2 9 0 0 4]


In [37]:
#subsetting--zeroth row -2nd element
print(array3)
s=array3[0,2]
print(s)

[[9 4 1 7 0]
 [8 4 5 1 9]]
1


In [39]:
print(array1)
array1[0:2]

[9 4 1 7 0]


array([9, 4])

In [18]:
#Slicing
print(array1)
array1[0:4:2]


[9 4 1 7 0]


array([9, 1])

In [4]:
#add
import numpy as np
array1=np.array([9,4,1,7,0])
array2=np.array([4,2,7,1,0])
s=np.add(array1,array2)
print(s)

[13  6  8  8  0]


In [5]:
#Subtract
array1=np.array([9,4,1,7,0])
array2=np.array([4,2,7,1,0])
s=np.subtract(array1,array2)
print(s)

[ 5  2 -6  6  0]


In [7]:
#divide
arr1=np.array([45])
arr2=np.array([5])
s=np.divide(arr1,arr2)
print(s)

[ 9.]


In [8]:
#exp
arr1=np.array([45])
s=np.exp(arr1)
print(s)

[  3.49342711e+19]


In [10]:
#sqrt
arr=np.array([625])
s=np.sqrt(arr)
print(s)

[ 25.]


In [11]:
#comparison
arr1=np.array([45])
arr2=np.array([5])
s=np.array_equal(arr1,arr2)
print(s)

False


In [12]:
#comparison
arr3=np.array([25])
arr4=np.array([25])
s=np.array_equal(arr3,arr4)
print(s)

True


In [16]:
#comparison
array3=np.array([[9,4,1,7,0],[8,4,5,1,9]])
array4=np.array([[4,2,7,1,0],[6,7,8,9,4]])
s=np.array_equal(array3,array4)
print(s)


False


In [19]:
#slicing
array1=np.array([9,4,1,7,0])
print(array1)
array1[:2]


[9 4 1 7 0]


array([9, 4])

In [22]:
#slicing-gives ist index of all rows
array3=np.array([[9,4,1,7,0],[8,4,5,1,9]])
print(array3)
array3[:,1]

[[9 4 1 7 0]
 [8 4 5 1 9]]


array([4, 4])

In [33]:
#array functions
array3=np.array([[9,4,1,7,0],[8,4,5,1,9]])
s=array3.sum()
print(s)
s=array3.max(axis=1)
print(s)

48
[9 9]


In [38]:
#Functions
array5=np.array([8,0,5,4,1,2,9,0,0,4])
s=array5.sum()
print(s)
s=array5.min()
print(s)
s=array5.max()
print(s)
s=array5.mean()
print(s)


33
0
9
3.3
